import { z } from "zod";
import { provenanceTypes } from "@/types/domain";

export const atlasCsvColumns = [
  "id",
  "monitored_entity",
  "collected_at",
  "published_at",
  "title",
  "summary",
  "content",
  "url",
  "domain",
  "platform",
  "author_name",
  "author_handle",
  "author_url",
  "actor_type",
  "category",
  "subcategory",
  "verification_status",
  "sentiment",
  "provenance_type",
  "confidence_level",
  "risk_score",
  "risk_level",
  "threat_level",
  "reach_value",
  "reach_type",
  "engagement_value",
  "velocity_score",
  "coordination_level",
  "target",
  "location_exposure",
  "evidence_type",
  "evidence_url",
  "screenshot_url",
  "indicators",
  "keywords",
  "status",
  "owner_team",
  "recommended_action",
  "analyst_notes"
] as const;

export type AtlasCsvColumn = (typeof atlasCsvColumns)[number];

export const atlasCsvRowSchema = z.object({
  id: z.string().optional(),
  monitored_entity: z.string().min(1),
  collected_at: z.string().datetime({ offset: true }),
  published_at: z.string().datetime({ offset: true }).or(z.literal("")),
  title: z.string().min(1),
  summary: z.string().optional(),
  content: z.string().optional(),
  url: z.string().url().or(z.literal("")).optional(),
  domain: z.string().optional(),
  platform: z.string().optional(),
  author_name: z.string().optional(),
  author_handle: z.string().optional(),
  author_url: z.string().url().or(z.literal("")).optional(),
  actor_type: z.string().optional(),
  category: z.string().optional(),
  subcategory: z.string().optional(),
  verification_status: z.string().optional(),
  sentiment: z.string().optional(),
  provenance_type: z.enum(provenanceTypes),
  confidence_level: z.enum(["high", "medium", "low"]),
  risk_score: z.string().optional(),
  risk_level: z.string().optional(),
  threat_level: z.string().optional(),
  reach_value: z.string().optional(),
  reach_type: z.enum(["native", "estimated", "unavailable"]),
  engagement_value: z.string().optional(),
  velocity_score: z.string().optional(),
  coordination_level: z.string().optional(),
  target: z.string().optional(),
  location_exposure: z.string().optional(),
  evidence_type: z.string().optional(),
  evidence_url: z.string().url().or(z.literal("")).optional(),
  screenshot_url: z.string().url().or(z.literal("")).optional(),
  indicators: z.string().optional(),
  keywords: z.string().optional(),
  status: z.string().optional(),
  owner_team: z.string().optional(),
  recommended_action: z.string().optional(),
  analyst_notes: z.string().optional()
});

export type AtlasCsvRow = z.infer<typeof atlasCsvRowSchema>;
